---

- name: restart elasticsearch
  service:
    name: elasticsearch
    state: restarted
    enabled: yes
  notify: Wait for elasticsearch to start

- name: Wait for elasticsearch to start
  wait_for:
    host: localhost
    port: "{{ elasticsearch_http_port }}"
